trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node 20'

# 1) "npm ci" in front-green-habit
- task: Npm@1
  displayName: 'Install dependencies (front-green-habit)'
  inputs:
    command: 'ci'
    workingDir: 'front-green-habit'   # Adjust if your folder name differs

# 2) "npm run build" in front-green-habit
- task: Npm@1
  displayName: 'Build (front-green-habit)'
  inputs:
    command: 'custom'
    workingDir: 'front-green-habit'
    customCommand: 'run build'

# 3) Deploy build folder to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'ecosentinel'
    package: '$(Build.SourcesDirectory)/front-green-habit/build'
