trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node 20'

- script: |
    cd front-green-habit
    npm ci
    npm run build
  displayName: 'Install & build front-green-habit'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'ecosentinel'
    package: '$(Build.SourcesDirectory)/front-green-habit/build'
