trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20'

# Install and build the front-end
- script: |
    cd front-green-habit
    npm ci
    npm run build
  displayName: 'npm ci and build (front-green-habit)'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'ecosentinel'
    package: 'front-green-habit'
