trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20'

# Install and build front-green-habit
- script: |
    cd front-green-habit
    npm ci
    npm run build
  displayName: 'Install & build front-green-habit'

# Deploy the build output to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'      # Your service connection name
    appName: 'ecosentinel'                       # Your Azure Web App name
    package: '$(Build.SourcesDirectory)/front-green-habit/build' 
